// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvXqG3IDfaM9v7jFb0q5O34NZpNuQeTm8',
    appId: '1:827353275906:web:d346e72fff0e522a94d11b',
    messagingSenderId: '827353275906',
    projectId: 'flutter-marombapp-347b3',
    authDomain: 'flutter-marombapp-347b3.firebaseapp.com',
    storageBucket: 'flutter-marombapp-347b3.appspot.com',
    measurementId: 'G-2DP1SD35R2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC9_XfnkxyL_MRHYAJ61urrdtKeEefbvw',
    appId: '1:827353275906:android:e3f835352eba275294d11b',
    messagingSenderId: '827353275906',
    projectId: 'flutter-marombapp-347b3',
    storageBucket: 'flutter-marombapp-347b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXO_nxqcZwqdQLBW3t4eocGp-LtmmAKmo',
    appId: '1:827353275906:ios:8bed8dc476c5706594d11b',
    messagingSenderId: '827353275906',
    projectId: 'flutter-marombapp-347b3',
    storageBucket: 'flutter-marombapp-347b3.appspot.com',
    iosBundleId: 'com.example.appMaromba',
  );
}
